# Generated by Django 5.0.1 on 2024-02-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
