# Generated by Django 5.0.1 on 2024-02-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0010_tagpost_alter_post_cat_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagpost',
            old_name='slag',
            new_name='slug',
        ),
    ]
